"""Regenerates the status/next-steps part of HANDOFF.md (section 2 and 3) from manifest.json + queue_flow.json.
usage: python tools/upd_handoff.py"""
import json, re, os
W = r"C:\Users\permr\fl_work\wwp"
m = json.load(open(os.path.join(W, "manifest.json"), encoding="utf-8"))
q = json.load(open(os.path.join(W, "_variants", "queue_flow.json"), encoding="utf-8"))
sl = json.load(open(os.path.join(W, "_variants", "brief", "shotlist.json"), encoding="utf-8-sig"))
order = [x["id"] for x in sl["timeline"]]
imgs_done = sorted([s["shot_id"] for s in m["scenes"] if s["type"] == "image"], key=lambda i: int(i[1:]))
clips_done = [s["shot_id"] for s in m["scenes"] if s["type"] == "video"]
clips_all = [x["id"] for x in sl["timeline"] if x.get("type") == "clip"]
clips_todo = [c for c in clips_all if c not in clips_done]
imgs_all = [x["id"] for x in sl["timeline"] if x.get("type") == "image"]
imgs_todo = [i for i in imgs_all if i not in imgs_done]
opt = [x["id"] for x in sl["timeline"] if x.get("priority") == "optional"]
status = f"""## 2. Exact status (auto-generated by tools/upd_handoff.py)
- Phase 0, 1 (refs), 5 (narration), 6 (music): DONE and pushed.
- Phase 3 images done ({len(imgs_done)}/{len(imgs_all)}): {', '.join(imgs_done)}. Pending: {', '.join(imgs_todo) or 'none'}.
- Phase 4 clips done ({len(clips_done)}/{len(clips_all)}): {', '.join(clips_done)}. Pending (timeline order): {', '.join(clips_todo) or 'none'}. Optional (last, only if > 150 credits left): {', '.join(opt)}.
- Flow credits: spent {m['flow_credits_spent']}, left {m['flow_credits_left']} (manifest). Stop below 150. Per-clip credits are in manifest scenes and in README (rebuild the README table from the manifest at the end).
- manifest phase: {m['phase']}.
"""
nxt = """## 3. NEXT STEPS in order
1. Continue the loop in section 9 (Flow clips in timeline order, Gemini images in parallel in a second tab, both interleaved so one waits while the other works).
2. Every ~10 files: `git add -A visuals manifest.json tools && git commit && git push`.
3. After the last core clip: optional clips if credits > 150; then README (credits per clip, Notes for the montage, Questions), manifest phase done, final push, ONE summary message to the user.
"""
p = os.path.join(W, "HANDOFF.md")
t = open(p, encoding="utf-8").read()
a = t.index("## 2. Exact status"); b = t.index("## 4. Gemini pipeline")
t = t[:a] + status + "\n" + nxt + "\n" + t[b:]
open(p, "w", encoding="utf-8").write(t)
print("ok", len(imgs_done), len(clips_done))
